import app.models.ai_suggestion  # noqa: F401
import app.models.audit  # noqa: F401
import app.models.customer  # noqa: F401
import app.models.feedback  # noqa: F401
import app.models.kb  # noqa: F401
import app.models.policy  # noqa: F401
import app.models.tag  # noqa: F401
import app.models.tenant  # noqa: F401
import app.models.ticket  # noqa: F401
import app.models.token  # noqa: F401
import app.models.user  # noqa: F401
import app.models.user_tenant  # noqa: F401